In [4]:
import numpy as np

In [3]:
# Solution of A x = b Using The QR Factorizations
#
from numpy import array
from scipy.linalg import qr, solve
#
print("Original (m x n) Matrix A  &  (m x 1) Vector b")
#
A = array([[ 1, 6, -1, 4],
           [1, -8, 2, 7],
           [4, 2,  5, 3]])
#
b = array([1, 2, 3])
#
print(A)
print(" ------------------ ")
print("b =", b)
#
print(" ------------------ ")
print(" QR - Factorization of A")
Q, R = qr(A)
print(" ------------------ ")
#
print("Matrix Q (m x m)")
print(Q)
print(" ---------- ")
print("Matrix Q^T Q = I (m x m)")
print(Q.T @ Q )
print(" ---------- ")
print("Matrix R (m x n)")
print(R)
print(" ---------- ")
print("Reconstruct A from QR Factorization")
print( Q @ R )
print(" ------------------ ")
print(" ---> Solve A x = b Using the QR Factorization of A")
# From A = Q R; we have A x = Q R x = b ==> R x = Q^t b
#      R^t R x = R^t Q^t b = (Q R)^t b = A^t b ")
x = solve(R.T @ R, A.T @ b)
print("Solution Vector x =", x)
print(" ------------------ ")
print("Verify that A x = b = ",  A @ x) 
print(" -------------> END")

Original (m x n) Matrix A  &  (m x 1) Vector b
[[ 1  6 -1  4]
 [ 1 -8  2  7]
 [ 4  2  5  3]]
 ------------------ 
b = [1 2 3]
 ------------------ 
 QR - Factorization of A
 ------------------ 
Matrix Q (m x m)
[[-0.23570226  0.56108361 -0.79349205]
 [-0.23570226 -0.82512295 -0.51343603]
 [-0.94280904  0.06600984  0.32673202]]
 ---------- 
Matrix Q^T Q = I (m x m)
[[ 1.00000000e+00  7.35728805e-17 -5.86083348e-17]
 [ 7.35728805e-17  1.00000000e+00  3.34218328e-17]
 [-5.86083348e-17  3.34218328e-17  1.00000000e+00]]
 ---------- 
Matrix R (m x n)
[[-4.24264069 -1.41421356 -4.94974747 -5.42115199]
 [ 0.         10.09950494 -1.88128033 -3.33349673]
 [ 0.          0.          1.40028008 -5.78782435]]
 ---------- 
Reconstruct A from QR Factorization
[[ 1.  6. -1.  4.]
 [ 1. -8.  2.  7.]
 [ 4.  2.  5.  3.]]
 ------------------ 
 ---> Solve A x = b Using the QR Factorization of A
Solution Vector x = [ 0.7081614  -0.0482955  -0.02995883  0.13791319]
 ------------------ 
Verify that A x = b =  [1

/var/folders/90/b16ybj8s2gv__lhxf5ttmvj40000gn/T/ipykernel_23900/782931056.py:38: LinAlgWarning: Ill-conditioned matrix (rcond=8.83496e-18): result may not be accurate.
  x = solve(R.T @ R, A.T @ b)


In [2]:
# QR Factorization of Rectangular ( m x n ) Matrix A
#
import numpy as np 
#from numpy import array
from scipy.linalg import qr
#from scipy.linalg import inv
#from scipy.linalg import pinv
from scipy.linalg import solve
#
print(" START ------------------> ")
# Enter m-Rows & n-Columns Of Coefficient Matrix A:
m = 5 ; n = 3
# If choice = 0, mode='economic' Q is (m x n) & R is (n x n)
# If choice = 1, mode='full'     Q is (m x m) & R is (m x n)
choice = 0
#
# Generate a Random (m x n) Matrix  A  With Each Integer Entry < 6:
A = np.random.randint(6, size=(m, n) )
#
print("The (", m, "x", n, ") Random Matrix A =") ; print(A)
#
# Generate a Random (m x 1) Vector b With Each Integer Entry < 9:
b = np.random.randint(9, size=(m, 1) )
#
print("The (", m, "x", 1, ") Random Vector b =") ; print(b)
print(" ------------------ ")
#
# QR - Factorization of A
if choice == 0: 
     Q, R = qr(A, mode='economic')
else:
     Q, R = qr(A, mode='full')
#
print("Matrix Q (", m, "x", n, ")  OR  (", m, "x", m, ")")
print(Q)
print(" ---------- ")
print("Matrix Q^T Q = I is (", n, " x ", n, ")  OR  (", m, " x ", m, ")")
print(Q.T @ Q )
print(" ---------- ")
print("Matrix R (", n, "x", n, ")  OR  (", m, "x", n, ")")
print(R)
print(" ---------- ")
print("Reconstruct A from QR")
print( Q @ R )
print(" ")
#
if choice == 0: 
  x = solve(R, Q.T @ b)
  print("---- QR Solution of  A x = Q R x = b -----")
  print("---- From The Solution of R x = Q.T b -----")
  print(" ")
  print("---- Solution Vector x =  -----")
  print(x)
  print(" ------------------ ")
  print("Compute Residual = A x - b ") 
  print( A @ x - b)
  print(" ")
#
#################################################################
#
print("----- QR Solution of A.T A x = R.T R x = R.T Q.T b = A.T b -----")
print("----- From The Solution of: R.T R x = A.T b -----")
print(" ")
print("----- Solution Vector x  of: R.T R x = A.T b  -----")
x = solve(R.T @ R, A.T @ b)
print(x)
print(" ")
#
print("----- Solution Vector x of:  A.T A x = A.T b  -----")
x = solve(A.T @ A, A.T @ b)
print(x)
print(" ")
#
print("----- Compute Residual = A.T A x - A.T b  -----") 
print( A.T @ A @ x - A.T @ b) 
print(" <------------------ END ")


 START ------------------> 
The ( 5 x 3 ) Random Matrix A =
[[3 4 0]
 [3 5 4]
 [3 5 2]
 [3 2 5]
 [4 0 2]]
The ( 5 x 1 ) Random Vector b =
[[7]
 [0]
 [1]
 [4]
 [2]]
 ------------------ 
Matrix Q ( 5 x 3 )  OR  ( 5 x 5 )
[[-0.41602515 -0.24281475 -0.60785606]
 [-0.41602515 -0.44010174  0.35645652]
 [-0.41602515 -0.44010174 -0.13602116]
 [-0.41602515  0.15175922  0.6646237 ]
 [-0.5547002   0.72844426 -0.20790225]]
 ---------- 
Matrix Q^T Q = I is ( 3  x  3 )  OR  ( 5  x  5 )
[[ 1.00000000e+00 -2.72920193e-17  1.61371080e-16]
 [-2.72920193e-17  1.00000000e+00  1.53609455e-16]
 [ 1.61371080e-16  1.53609455e-16  1.00000000e+00]]
 ---------- 
Matrix R ( 3 x 3 )  OR  ( 5 x 3 )
[[-7.21110255 -6.65640235 -5.68567701]
 [ 0.         -5.068758   -0.42492582]
 [ 0.          0.          4.06109775]]
 ---------- 
Reconstruct A from QR
[[3.0000000e+00 4.0000000e+00 2.5806139e-15]
 [3.0000000e+00 5.0000000e+00 4.0000000e+00]
 [3.0000000e+00 5.0000000e+00 2.0000000e+00]
 [3.0000000e+00 2.0000000e+00 5.00

In [21]:
A = np.array([[-3, 1], [-1, 1],[0,1],[2,1]])
b = np.array([0,1,2,3])
b = b.T
A.T @ b
np.linalg.solve(A.T @ A, A.T @ b)

array([0.61538462, 1.80769231])