##### Joshua Boehm
##### 10 October 2022
##### MATH 3423

# Libraries

In [1]:
import numpy as np
import scipy as sp

# Preface


Let $A$ be a (4 x 3) randomly generated matrix `A = np.random.randint( 0, 5, size = (4, 3))` with integer elements in the interval [0, 5);<br>
let $b$ be a (4 x 1) randomly generated vector `b = np.random.randint( -1, 3, size = (4, 1))` with integer elements in the interval [-1, 3);<br>
and let $c$ be a (3 x 1) randomly generated vector `c = np.random.randint( -1, 3, size = (3, 1))` with integer elements in the interval [-1, 3).

In [2]:
# Assigning the randomly generated matrices to variables in order to manipulate below without mutating them.
m = 4 ; n = 3
a = np.random.randint(0,5, size = (m,n))
B = np.random.randint(-1,3, size = (4,1))
C = np.random.randint(-1,3, size = (3,1))

print(
f"Matrix A:\n{a}\n\n\
Matrix b:\n{B}\n\n\
Matrix c:\n{C}")

Matrix A:
[[3 3 1]
 [1 2 3]
 [3 1 1]
 [2 2 1]]

Matrix b:
[[ 1]
 [ 0]
 [-1]
 [ 2]]

Matrix c:
[[2]
 [0]
 [0]]


In [3]:
A = a
b = B
c = C

# Question 1

Find the $QR$ factorizations of $A$ and $A^T$ and use them to solve $Ax = b$ and $A^Ty=c$.

## QR factorization of $A$

In [18]:
# QR Factorization of Rectangular ( m x n ) Matrix A

from scipy.linalg import qr, solve

print(f"\
QR Factorization of Rectangular ( m x n ) Matrix A \n \
-------------------------------------------------- \n \
")
# Enter m-Rows & n-Columns Of Coefficient Matrix A:
m = 4 ; n = 3
# If choice = 0, mode='economic' Q is (m x n) & R is (n x n)
# If choice = 1, mode='full'     Q is (m x m) & R is (m x n)
choice = 0

print(f"The {m} x {n} Matrix A: \n{A}\n")
print(f"The {m} x {1} Matrix b: \n{b}\n")
print(f"The {n} x {1} Matrix c: \n{c}")
print("--------------------------------------------------")

# QR - Factorization of A
# if choice == 0: 
#      Q, R = qr(A, mode='economic')
# else:
#      Q, R = qr(A, mode='full')

'''
# This is just to see what's going on.
print("Matrix Q (", m, "x", n, ")  OR  (", m, "x", m, ")")
print(Q)
print("--------------------------------------------------")
print("Matrix Q^T Q = I is (", n, " x ", n, ")  OR  (", m, " x ", m, ")")
print(Q.T @ Q )
print("--------------------------------------------------")
print("Matrix R (", n, "x", n, ")  OR  (", m, "x", n, ")")
print(R)
print("--------------------------------------------------")
print("Reconstruct A from QR")
print( Q @ R )
'''


Q, R = qr(A, mode='economic')
x = solve(R, Q.T @ b)
print("---- QR Solution of  A x = Q R x = b -----")
print("---- From The Solution of R x = Q.T b -----")
print(" ")
print("---- Solution Vector x =  -----")
print(x.round(2))

print("=========================================================")

QR Factorization of Rectangular ( m x n ) Matrix A 
 -------------------------------------------------- 
 
The 4 x 3 Matrix A: 
[[3 3 1]
 [1 2 3]
 [3 1 1]
 [2 2 1]]

The 4 x 1 Matrix b: 
[[ 1]
 [ 0]
 [-1]
 [ 2]]

The 3 x 1 Matrix c: 
[[2]
 [0]
 [0]]
--------------------------------------------------
---- QR Solution of  A x = Q R x = b -----
---- From The Solution of R x = Q.T b -----
 
---- Solution Vector x =  -----
[[-0.53]
 [ 1.28]
 [-0.63]]


## QR factorization of $A^T$

In [61]:
# Q, R = qr(A, mode = 'economic')

# z = solve(R.T, c)
# y = solve(Q @ Q.T, Q @ z)

# print(y.round(2))


Q, R = qr(A.T, mode = 'economic')

print(Q.round(2))
print(" ")
print(R.round(2))

y = solve(R.T @ R, A @ c)
print(" ")
print(y.round(2))

A.T @ y - c

[[-0.69  0.35  0.63]
 [-0.69 -0.04 -0.72]
 [-0.23 -0.93  0.27]]
 
[[-4.36 -2.75 -2.98 -2.98]
 [ 0.   -2.53  0.08 -0.31]
 [ 0.    0.    1.45  0.09]]
 
[[-0.62]
 [-0.36]
 [ 0.82]
 [ 0.87]]


/var/folders/90/b16ybj8s2gv__lhxf5ttmvj40000gn/T/ipykernel_30424/3152074972.py:15: LinAlgWarning: Ill-conditioned matrix (rcond=1.0502e-17): result may not be accurate.
  y = solve(R.T @ R, A @ c)


array([[ 8.88178420e-16],
       [-4.44089210e-16],
       [ 3.33066907e-16]])

As is typical with $A^T$, the resulting matrices are ill-conditioned and never seem accurate.

# Question 2

Find the $SVD$ factorizations of $A$ and $A^T$ and use them to solve $Ax=b$ and $A^Ty=c$.

## Solutions

### $Ax = b$ variant

In [46]:
# Compute The Singular Value Decomposition of (M x N) Matrix A
# The Pseudo-Inverse of A
# Solve Ax = b using The SVD/Pseudo-Inverse
#
import numpy as np
from scipy.linalg import diagsvd
from scipy.linalg import pinv
#from scipy.linalg import inv
from scipy.linalg import svd
#
# Enter m-Rows & n-Columns Of Coefficient Matrix A:
U, sigma, VT = svd(A)
Sigma = diagsvd(sigma, m, n)
PseudoA = (VT).T @ pinv(Sigma) @ U.T 
x = PseudoA @  b


print(f"\
------------------------------------\n\
Perform Singular Value Decomposition\n\
------------------------------------\n\
The A matrix:\n\
{A}\n\
------------------------------------\n\
The ({m} x {m}) U Matrix\n\
{U}\n\
------------------------------------\n\
The ({m} x {n}) Singular Values of A\n\
{Sigma}\n\
------------------------------------\n\
The ({n} x {n} V^T Matrix\n\
{VT}\n\
------------------------------------\n\
Reconstructed Original ({m} x {n} Matrix A From SVD Factors\n\
{U @ Sigma @ VT}\n\
------------------------------------\n\
")

#The Pseudo-Inverse of A is Given by: A^+ = V Sigma^+ U^T
#
print(f"Compute The ( {n} x {m}) Sigma^+ Singular Values of The Pseudo-Inverse of A\n\
{pinv(Sigma)}\n\
------------------------------------")
if m > n:
    print(f"---Verify  Sigma^+ * Sigma = I; If A Has Independent Columns ----\n\
{pinv(Sigma) @ Sigma}\n\
------------------------------------")
elif m < n:
    print(f"---Verify  Sigma * Sigma^+ = I; If A Has Independent Rows ----\n\
{Sigma @ pinv(Sigma)}\n\
------------------------------------")

print(f"\
Compute The Pseudo-Inverse of A <-- (VT).T @ pinv(Sigma) @ U.T\n\
{PseudoA}\n\
------------------------------------\n\
Compute The Pseudo-Inverse of A <-- pinv(A)\n\
{pinv(A)}\n\
------------------------------------\n\
")
print(f"Compute The ( {n} x {m}) Sigma^+ Singular Values of The Pseudo-Inverse of A\n\
{pinv(Sigma)}\n\
------------------------------------")
if m > n:
    print(f"---Verify  A^+ * A = I; If A Has Independent Columns ----\n\
{PseudoA @ A}\n\
------------------------------------")
elif m < n:
    print(f"---Verify  A * A^+ = I; If A Has Independent Rows ----\n\
{A @ PseudoA }\n\
------------------------------------")


print(f"\
Verify A * A^+ * A = A\n\
{A @ PseudoA @ A}\n\
------------------------------------\n\
Verify that A^+ * A * A^+\n\
{PseudoA @ A @ PseudoA}\n\
------------------------------------\n\
Solve A x = b Using The Pseudo-Inverse of A\m\
From  x = A^+ b = V Sigma^+ U^T b\n\
------------------------------------\n\
Solution Vector x =\n\
{x.round(2)}\n\
")

------------------------------------
Perform Singular Value Decomposition
------------------------------------
The A matrix:
[[3 3 1]
 [1 2 3]
 [3 1 1]
 [2 2 1]]
------------------------------------
The (4 x 4) U Matrix
[[-0.62576268  0.29780378  0.5318758  -0.48666426]
 [-0.46513892 -0.86339719 -0.16277336 -0.10814761]
 [-0.44737015  0.39839638 -0.79888441 -0.05407381]
 [-0.43809451  0.08448975  0.22890319  0.86518091]]
------------------------------------
The (4 x 3) Singular Values of A
[[6.80551246 0.         0.        ]
 [0.         2.2997395  0.        ]
 [0.         0.         1.18160842]
 [0.         0.         0.        ]]
------------------------------------
The (3 x 3 V^T Matrix
[[-0.6701518  -0.6070263  -0.42710143]
 [ 0.60623509 -0.1156684  -0.78682898]
 [-0.42822375  0.78621873 -0.44551603]]
------------------------------------
Reconstructed Original (4 x 3 Matrix A From SVD Factors
[[3. 3. 1.]
 [1. 2. 3.]
 [3. 1. 1.]
 [2. 2. 1.]]
------------------------------------

Com

Utilizing the SVD decomposition and multiplying the pseudoinverse of $A$ with $b$ yields the following solution vector:
$$x = \begin {bmatrix} -0.22222222 \\ 2.88888889 \\ -9.22222222 \end {bmatrix}$$

### $A^Ty = c$ variant

In [58]:
VT.T @ Sigma.T @ U.T

y = U @ pinv(Sigma.T) @ VT @ c

print(y.round(2))

A.T @ y - c

# U, sigma, VT = svd(A.T)
# Sigma = diagsvd(sigma, n, m)
# PseudoAT = (VT).T @ pinv(Sigma) @ U.T 
# x = PseudoAT @  c


# print(f"\
# ------------------------------------\n\
# Perform Singular Value Decomposition\n\
# ------------------------------------\n\
# The A^T matrix:\n\
# {A.T}\n\
# ------------------------------------\n\
# The ({n} x {n}) U Matrix\n\
# {U}\n\
# ------------------------------------\n\
# The ({n} x {m}) Singular Values of A^T\n\
# {Sigma}\n\
# ------------------------------------\n\
# The ({m} x {m}) V^T Matrix\n\
# {VT}\n\
# ------------------------------------\n\
# Reconstructed Original ({n} x {m}) Matrix A From SVD Factors\n\
# {U @ Sigma @ VT}\n\
# ------------------------------------\n\
# ")

# #The Pseudo-Inverse of A is Given by: A^+ = V Sigma^+ U^T
# #
# print(f"Compute The ( {m} x {n}) Sigma^+ Singular Values of The Pseudo-Inverse of A^T\n\
# {pinv(Sigma)}\n\
# ------------------------------------")
# if n > n:
#     print(f"---Verify  Sigma^+ * Sigma = I; If A Has Independent Columns ----\n\
# {pinv(Sigma) @ Sigma}\n\
# ------------------------------------")
# elif n < n:
#     print(f"---Verify  Sigma * Sigma^+ = I; If A Has Independent Rows ----\n\
# {Sigma @ pinv(Sigma)}\n\
# ------------------------------------")

# print(f"\
# Compute The Pseudo-Inverse of A^T <-- (VT).T @ pinv(Sigma) @ U.T\n\
# {PseudoAT}\n\
# ------------------------------------\n\
# Compute The Pseudo-Inverse of A^T <-- pinv(A)\n\
# {pinv(A.T)}\n\
# ------------------------------------\n\
# ")
# print(f"Compute The ( {n} x {n}) Sigma^+ Singular Values of The Pseudo-Inverse of A^T\n\
# {pinv(Sigma)}\n\
# ------------------------------------")
# if n > m:
#     print(f"---Verify  A^+ * A = I; If A Has Independent Columns ----\n\
# {PseudoAT @ A.T}\n\
# ------------------------------------")
# elif n < m:
#     print(f"---Verify  A * A^+ = I; If A Has Independent Rows ----\n\
# {A.T @ PseudoAT }\n\
# ------------------------------------")


# print(f"\
# Verify A^T * A^T^+ * A^T = A^T\n\
# {A.T @ PseudoAT @ A.T}\n\
# ------------------------------------\n\
# Verify that A^T^+ * A^T * A^T^+\n\
# {PseudoAT @ A.T @ PseudoAT}\n\
# ------------------------------------\n\
# Solve A^T y = c Using The Pseudo-Inverse of A^T\n\
# From  y = A^T^+ c = V Sigma^+ U^T b\n\
# ------------------------------------\n\
# Solution Vector x =\n\
# {x}\n\
# ")

[[-0.11]
 [-0.25]
 [ 0.88]
 [-0.04]]


array([[-2.22044605e-16],
       [ 3.33066907e-16],
       [ 5.55111512e-16]])

The SVD decomposition is well utilized to find the solution:
$$x = \begin {bmatrix} 1 \\ 4 \\ -3 \\ -2\end {bmatrix}$$

# Question 3

Solve $A^TAx = A^Tb$ using the Cholesky factorization.

## Solution

In [63]:
from numpy.linalg import cholesky

Atranspose_A = A.T @ A

L = cholesky(Atranspose_A)
x =solve(L @ L.T, A.T @ b)
print(f" \
The A^T A matrix: \n {Atranspose_A} \n\n \
The Cholesky factorization:\n\n\
L matrix:\n{L}\n\n\
L.T matrix:\n{L.T}\n\n\
Solving for x by using L L^T x =  A^T b:\n\
{x.round(2)}")

 The A^T A matrix: 
 [[23 18 11]
 [18 18 12]
 [11 12 12]] 

 The Cholesky factorization:

L matrix:
[[4.79583152 0.         0.        ]
 [3.75325945 1.97814142 0.        ]
 [2.29365855 1.71438923 1.94935887]]

L.T matrix:
[[4.79583152 3.75325945 2.29365855]
 [0.         1.97814142 1.71438923]
 [0.         0.         1.94935887]]

Solving for x by using L L^T x =  A^T b:
[[-0.53]
 [ 1.28]
 [-0.63]]


Cholesky once again proves to be an amazing example of specialized matrix factorization. It successfully finds the solution vector:
 $$x = \begin {bmatrix} -0.22222222 \\ 2.88888889 \\ -9.22222222 \end {bmatrix}$$

# Question 4

Solve $A^TAx = A^Tb$ using the $QR$ factorization.

## Solution

In [10]:
Q, R = qr(Atranspose_A)

print(f" \
The A^T A matrix: \n {Atranspose_A} \n\n \
The QR factorization:\n\n\
Q matrix:\n{Q}\n\n\
R matrix:\n{R}\n\n\
Solving for x by using QR x = b:\n\
{solve(Q @ R, A.T @ b)}")

 The A^T A matrix: 
 [[23 18 11]
 [18 18 12]
 [11 12 12]] 

 The QR factorization:

Q matrix:
[[-0.73696754  0.65920129  0.14944064]
 [-0.5767572  -0.49799226 -0.64757613]
 [-0.35246273 -0.56343355  0.74720322]]

R matrix:
[[-31.20897307 -27.87659812 -19.25728215]
 [  0.          -3.85944001  -5.4858955 ]
 [  0.           0.           2.83937224]]

Solving for x by using QR x = b:
[[-0.52631579]
 [ 1.28070175]
 [-0.63157895]]


The QR factorization also finds the same solution vector:
$$x = \begin {bmatrix} -0.22222222 \\ 2.88888889 \\ -9.22222222 \end {bmatrix}$$

# Question 5

Solve $A^TAx = A^Tb$ using the $SVD$ factorization.

## Solution

In [11]:
print(f"\
The A matrix:\n\
{A}\n\n\
The A.T matrix:\n\
{A.T}\n\n\
")

U, sigma, VT = svd(A)
Sigma = diagsvd(sigma, 4, 3)

print(f"U:\n{U}\n\nSigma:\n{Sigma}\n\nV^T:\n{VT}\n")
# print(f"The reconstruction of A with SVD:\n{U @ Sigma @ VT}\n\n\
# The construction of A^T with SVD:\n{VT.T @ Sigma.T @ U.T}")
x = solve(VT.T @ Sigma.T @ Sigma @ VT, VT.T @ Sigma.T @ U.T @ b)
print(f"\
The solution vector x using V Sigma Sigma^T V x = V Sigma^T U^T b\n\
{x}")

The A matrix:
[[3 3 1]
 [1 2 3]
 [3 1 1]
 [2 2 1]]

The A.T matrix:
[[3 1 3 2]
 [3 2 1 2]
 [1 3 1 1]]


U:
[[-0.62576268  0.29780378  0.5318758  -0.48666426]
 [-0.46513892 -0.86339719 -0.16277336 -0.10814761]
 [-0.44737015  0.39839638 -0.79888441 -0.05407381]
 [-0.43809451  0.08448975  0.22890319  0.86518091]]

Sigma:
[[6.80551246 0.         0.        ]
 [0.         2.2997395  0.        ]
 [0.         0.         1.18160842]
 [0.         0.         0.        ]]

V^T:
[[-0.6701518  -0.6070263  -0.42710143]
 [ 0.60623509 -0.1156684  -0.78682898]
 [-0.42822375  0.78621873 -0.44551603]]

The solution vector x using V Sigma Sigma^T V x = V Sigma^T U^T b
[[-0.52631579]
 [ 1.28070175]
 [-0.63157895]]


Once again the solution vector is shown to be: $$x = \begin {bmatrix} -0.22222222 \\ 2.88888889 \\ -9.22222222 \end {bmatrix}$$

The below was a misguided attempt to solve the above. After my question in class clarified the process, I decided to change; I just didn't want to delete my thought process.

In [12]:
# m = 4; n = 3
# U, sigma, VT = svd(A)
# Sigma = diagsvd(sigma, m, n)
# #PseudoA = (VT).T @ pinv(Sigma) @ U.T 
# #x = PseudoA @ Atranspose_A @ b

# print(f"\
# A^T A:\n\
# {Atranspose_A}\n\
# A^T A from the SVD breakdown:\n\
# {VT.T @ Sigma.T @ U.T @ U @ Sigma @ VT}\
# \
# ")

# print(f"\
# ------------------------------------\n\
# Perform Singular Value Decomposition\n\
# ------------------------------------\n\
# The A^T A matrix:\n\
# {Atranspose_A}\n\
# ------------------------------------\n\
# The ({m} x {m}) U Matrix\n\
# {U}\n\
# ------------------------------------\n\
# The ({m} x {n}) Singular Values of A\n\
# {Sigma}\n\
# ------------------------------------\n\
# The ({n} x {n}) V^T Matrix\n\
# {VT}\n\
# ------------------------------------\n\
# Reconstructed Original ({m} x {n}) Matrix A From SVD Factors\n\
# {U @ Sigma @ VT}\n\
# ------------------------------------\n\
# ")

# #The Pseudo-Inverse of A is Given by: A^+ = V Sigma^+ U^T
# #
# print(f"Compute The ( {n} x {m}) Sigma^+ Singular Values of The Pseudo-Inverse of A\n\
# {pinv(Sigma)}\n\
# ------------------------------------")
# if m > n:
#     print(f"---Verify  Sigma^+ * Sigma = I; If A Has Independent Columns ----\n\
# {pinv(Sigma) @ Sigma}\n\
# ------------------------------------")
# elif m < n:
#     print(f"---Verify  Sigma * Sigma^+ = I; If A Has Independent Rows ----\n\
# {Sigma @ pinv(Sigma)}\n\
# ------------------------------------")

# print(f"\
# Compute The Pseudo-Inverse of A <-- (VT).T @ pinv(Sigma) @ U.T\n\
# {PseudoA}\n\
# ------------------------------------\n\
# Compute The Pseudo-Inverse of A <-- pinv(A)\n\
# {pinv(Atranspose_A)}\n\
# ------------------------------------\n\
# ")
# print(f"Compute The ( {n} x {m}) Sigma^+ Singular Values of The Pseudo-Inverse of A\n\
# {pinv(Sigma)}\n\
# ------------------------------------")
# if m > n:
#     print(f"---Verify  A^+ * A = I; If A Has Independent Columns ----\n\
# {PseudoA @ Atranspose_A}\n\
# ------------------------------------")
# elif m < n:
#     print(f"---Verify  A * A^+ = I; If A Has Independent Rows ----\n\
# {Atranspose_A @ PseudoA }\n\
# ------------------------------------")


# print(f"\
# Verify A * A^+ * A = A\n\
# {Atranspose_A @ PseudoA @ Atranspose_A}\n\
# ------------------------------------\n\
# Verify that A^+ * A * A^+\n\
# {PseudoA @ Atranspose_A @ PseudoA}\n\
# ------------------------------------\n\
# Solve A x = b Using The Pseudo-Inverse of A^T A\n\
# From  x = A^+ b = V Sigma^+ U^T b\n\
# ------------------------------------\n\
# Solution Vector x =\n\
# {A.T @ x}\n\
# ")



# Question 6

Find the eigenvalues and the corresponding eigenvectors of $A^TA$ and $AA^T$.

## Solution

In [13]:
print(f"\
The eigen values of A^T A:\n\
{np.linalg.eig(A.T @ A)}\n\n\
The eigen values of A A^T:\n\
{np.linalg.eig(A @ A.T)}\
")

The eigen values of A^T A:
(array([46.31499979,  5.28880176,  1.39619845]), array([[-0.6701518 , -0.60623509,  0.42822375],
       [-0.6070263 ,  0.1156684 , -0.78621873],
       [-0.42710143,  0.78682898,  0.44551603]]))

The eigen values of A A^T:
(array([4.63149998e+01, 5.28880176e+00, 9.05581676e-16, 1.39619845e+00]), array([[ 0.62576268,  0.29780378, -0.48666426,  0.5318758 ],
       [ 0.46513892, -0.86339719, -0.10814761, -0.16277336],
       [ 0.44737015,  0.39839638, -0.05407381, -0.79888441],
       [ 0.43809451,  0.08448975,  0.86518091,  0.22890319]]))


The eigenvalues are identical with the exception of the larger resulting square matrix, $AA^T$, which has an additional eigenvalue equal to 0. The eigenvectors are shown but not very cleanly.

# Question 7

Show numerically that for any rectangular matrix:
$$
AA^+A = A \quad{and}\quad A^+AA^+ = A^+
$$

## Solution

In [14]:
print(f"We'll show numerically that A A^pseudoinverse is equalt to the identity matrix.\n\
\
{pinv(A) @ A}")

We'll show numerically that A A^pseudoinverse is equalt to the identity matrix.
[[ 1.00000000e+00  2.35922393e-16  1.45716772e-16]
 [ 5.55111512e-16  1.00000000e+00 -1.66533454e-16]
 [-2.49800181e-16 -3.60822483e-16  1.00000000e+00]]


This would indicate that if we post-multiply A by the pseudoinverse of A, the resulting matrix is the identity matrix. There is a certain level of roudning error, as is typical with matricies in computer programming.